name: Calculate Bokshi index
on:
    workflow_dispatch:
    schedule:
        - cron: "0 */2 * * *" # runs every 2 h

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              
            - name: Install dependencies 
              run: pip install -r ./requirements.txt 

            - name: run script & generate HTML
              env:
                API_KEY: ${{secrets.API_KEY}}
                APP_KEY: ${{secrets.APP_KEY}}
                MAC: ${{secrets.MAC}}
              run: python main.py > ./result.html

            - name: Check where's the result
              run: ls -a
              
                    
              # Deploy to GitHub Pages
            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v4
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./
