name: run the main script
on:
    workflow_dispatch:
    schedule:
        - cron: "0 */2 * * *" # runs every 2 h

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              
            - name: Install dependencies 
              run: pip install -r ./requirements.txt 

            - name: run script & generate HTML
              env:
                API_KEY: ${{secrets.API_KEY}}
                APP_KEY: ${{secrets.APP_KEY}}
                MAC: ${{secrets.MAC}}
              run: python main.py > result.html
              
            - name: Commit result.html to GitHub Pages
              run: |
                git config --global user.email "yura.nuke22@gmail.com"
                git config --global user.name "Yurii"
                git checkout -b result-update 
                git add result.html
                git commit -m "Update result.html"
                git push origin result-update
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
