name: run the main script
on:
    workflow_dispatch:
    schedule:
        - cron: "0 */2 * * *" # runs every 2 h

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              
            - name: Install dependencies 
              run: pip install -r ./requirements.txt 

            - name: run script
              env:
                API_KEY: ${{secrets.API_KEY}}
                APP_KEY: ${{secrets.APP_KEY}}
                MAC: ${{secrets.MAC}}
              run: python main.py

            - name: Generate HTML file
              run: python my_script.py > result.html
              
            - name: report pompletion          
              run: echo "Workflow completed!"
